Repository knative-extensions/kn-plugin-service-log, pull requests merged in 2021-09, with the labels that each got.

#6 [Automated] Format markdown
  README.md
Labels: cla: yes, approved, lgtm, size/XS

#8 [Automated] Fix misspellings
  README.adoc
  hack/build.sh
Labels: cla: yes, approved, lgtm, size/XS

#13 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/XL

#17 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/M

#20 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, size/S, lgtm

#19 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/M

#22 Update to latest knative deps
  cmd/kn-service-log.go
  go.mod
  go.sum
  hack/build-flags.sh
  hack/build.sh
  hack/global_vars.sh
  pkg/log_command.go
  pkg/plugin/plugin.go
  pkg/tail.go
  test/e2e-tests.sh
  test/presubmit-tests.sh
  vendor/modules.txt
Labels: cla: yes, approved, size/L, lgtm

#23 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, size/S, lgtm

#24 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/knative.dev/kn-plugin-service-log/LICENSE
  vendor/modules.txt
Labels: cla: yes, approved, size/L, lgtm
