Repository knative-extensions/kn-plugin-service-log, pull requests merged in 2022-03, with the labels that each got.

#39 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/value/name.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_386.go
  vendor/golang.org/x/sys/unix/syscall_linux_alarm.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_mipsx.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/syscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_386.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/term/codereview.cfg
  vendor/golang.org/x/term/term.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#42 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#40 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#41 Added namespace flag
  .gitignore
  go.mod
  go.sum
  pkg/log_command.go
  pkg/namespaced.go
  pkg/namespaced_test.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/gotest.tools/v3/LICENSE
  vendor/gotest.tools/v3/assert/assert.go
  vendor/gotest.tools/v3/assert/cmp/compare.go
  vendor/gotest.tools/v3/assert/cmp/result.go
  vendor/gotest.tools/v3/internal/assert/assert.go
  vendor/gotest.tools/v3/internal/assert/result.go
  vendor/gotest.tools/v3/internal/difflib/LICENSE
  vendor/gotest.tools/v3/internal/difflib/difflib.go
  vendor/gotest.tools/v3/internal/format/diff.go
  vendor/gotest.tools/v3/internal/format/format.go
  vendor/gotest.tools/v3/internal/source/defers.go
  vendor/gotest.tools/v3/internal/source/source.go
  vendor/modules.txt
Labels: size/XXL, approved, ok-to-test, lgtm, kind/enhancement
