Repository knative-extensions/kn-plugin-service-log, pull requests merged in 2022-04, with the labels that each got.

#44 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#47 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#48 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#46 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/XL

#45 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, size/XS

#49 Remove unused klog library
  go.mod
  pkg/log_command.go
  third_party/VENDOR-LICENSE/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#50 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/L, lgtm

#51 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
